"""Carga el catálogo maestro de insumos de Laura desde la planilla oficial."""
import json
import sys
from pathlib import Path

# Corregir path
sys.path.insert(0, '/Users/agustin/.openclaw/workspace/tecman')

INSUMOS = {
    "Insumos Librería": [
        "Abrochadora N° 50",
        "Alfileres",
        "Banda elástica chica",
        "Bibliorato oficio",
        "Bolsa cristal 30x40",
        "Broche para abrochadora N°10-50",
        "Broches clips N° 6",
        "Cajas N° 3 (palomares)",
        "Cartel oportunidades A5",
        "Cinta bifaz",
        "Cinta Dabra",
        "Cinta de embalar transparente",
        "Cinta scotch 12x60",
        "Corrector",
        "Cuaderno cuadriculado grande",
        "Cuaderno rayado grande",
        "Cúter",
        "Etiqueta sin cambio ni devolución",
        "Etiqueta Zebra 250x800",
        "Etiqueta Zebra 50x25 térmica eco x250u",
        "Etiquetadora precio",
        "Fibrón punta cuadrada negro",
        "Fibrón punta cuadrada rojo",
        "Folio oficio",
        "Guías internas",
        "Goma",
        "Lapicera azul",
        "Lapicera negra",
        "Lápiz negro",
        "Moño mágico op. x100u N°25 plata",
        "Moño mágico op. x100u N°25 rojo",
        "Moño mágico op. x50u N°50 plata",
        "Moño mágico op. x50u N°50 rojo",
        "Precio autoadhesivo efectivo/tarjeta",
        "Precio oportunidad calzado",
        "Precio oportunidad indumentaria",
        "Regla 30 cm",
        "Resaltador amarillo",
        "Resma A4 Nat",
        "Rollo de film negro",
        "Rollo de film transparente",
        "Rollo fiscal térmico Dexter",
        "Rollo fiscal térmico Moov",
        "Rollo fiscal térmico Stock Center",
        "Rollo para etiquetadora amarillo",
        "Rollo para etiquetadora blanco",
        "Rollo para etiquetadora verde",
        "Rollo termocontraíble",
        "Sacapuntas",
        "Sobre papel madera 19x24",
        "Sobre papel madera 30x40",
        "Tacos",
        "Talonario comprobantes de gastos",
        "Talonario de memorándum",
        "Talonario vale a descontar",
        "Tijera",
        "Tinta para sello negra",
        "Voligoma",
    ],
    "Insumos Limpieza": [
        "Algodón",
        "Armazón mopa 1m",
        "Armazón mopa 60cm",
        "Balde",
        "Bolsa de residuo 45x60",
        "Bolsa de residuo 80x110",
        "Cif crema",
        "Desodorante de ambiente",
        "Detergente 750cc",
        "Escobilla baño",
        "Escobillones chicos",
        "Esponja acero",
        "Esponja amarilla",
        "Franela",
        "Guantes de cocina",
        "Insecticida mata cucarachas/arañas",
        "Insecticida mata mosquitos",
        "Jabón de tocador",
        "Jabón líquido x5 lts",
        "Limpia vidrios Cif",
        "Lustramueble",
        "Pala chica",
        "Palo escoba",
        "Papel higiénico x300m",
        "Papel higiénico x80m",
        "Plumero N°2",
        "Rejilla",
        "Repuesto barredor 1m (mopa)",
        "Repuesto barredor 60cm (mopa)",
        "Secador",
        "Secador de vidrio",
        "Sopapa",
        "Sutter spolvero",
        "Toallas de papel",
        "Trapo de piso",
    ],
}

# Escribir como JSON en data/insumos_catalogo.json
out = Path('/Users/agustin/.openclaw/workspace/tecman/data/insumos_catalogo.json')
out.write_text(json.dumps(INSUMOS, indent=2, ensure_ascii=False))
print(f"OK - guardado en {out}")
print(f"Total: {sum(len(v) for v in INSUMOS.values())} ítems en {len(INSUMOS)} categorías")
