"""Categorias de materiales/stock con su jerarquia.

Estructura:
    - nombre: nombre de la categoria padre
    - items: lista de sub-items (vacia si la categoria no tiene sub-items)
    - guia: dict opcional con archivo a descargar/mostrar; si archivo esta
      vacio se muestra como "proximamente".
"""

MATERIAL_CATEGORIAS = [
    {
        "nombre": "Luminaria",
        "items": [],
        # Guia visible al seleccionar Luminaria. Si "archivo" esta vacio o
        # None, se muestra como "proximamente" (deshabilitado).
        "guia": {"archivo": "LAMPARAS_BASICAS.docx", "titulo": "Ver guia de luminaria"},
        "items": [
            "Artefactos de embutir",
            "Artefactos de aplicar",
            "Tubos LED",
            "Zócalos",
            "Lámparas AR111",
            "Lámparas PAR30",
            "Lámparas globo",
            "Lámparas campana",
            "Lámparas HQI",
        ],
    },
    {
        "nombre": "Insumos de electricidad",
        "items": [
            "Termica",
            "Cables unipolares 2.5",
            "Cables unipolares 1.5",
            "Cables unipolares (Varios)",
            "Disyuntor",
            "Tomas simples",
            "Tomas dobles",
            "Cable canal",
            "Bandejas",
            "Garrafas R22",
            "Garrafa 410",
            "Garrafa Gas Map (para soldar caneria de aires)",
        ],
    },
    {"nombre": "Pinturas", "items": []},
    {
        "nombre": "Accesorios para pintar",
        "items": [
            "Pincel",
            "Cinta de papel",
            "Bolsa de trapo",
            "Aguarras",
            "Thinner",
            "Rodillo de pelo corto",
            "Rodillo de pelo largo",
        ],
    },
    {
        "nombre": "Cortinas de aires",
        "items": [
            "90cm Negra",
            "90cm Blanca",
            "1.20 Negra",
            "1.20 Blanca",
        ],
    },
    {"nombre": "Placas de Durlock", "items": []},
    {"nombre": "Masilla de Durlock", "items": []},
    {"nombre": "Cinta para Durlock", "items": []},
    {
        "nombre": "Reparacion de techos",
        "items": [
            "Membrana liquida",
            "Rollo de manta / venda",
        ],
    },
    {
        "nombre": "Insumos Librería",
        "items": [
            "Abrochadora N° 50",
            "Alfileres",
            "Banda elástica chica",
            "Bibliorato oficio",
            "Bolsa cristal 30x40",
            "Broche para abrochadora N°10-50",
            "Broches clips N° 6",
            "Cajas N° 3 (palomares)",
            "Cartel oportunidades A5",
            "Cinta bifaz",
            "Cinta Dabra",
            "Cinta de embalar transparente",
            "Cinta scotch 12x60",
            "Corrector",
            "Cuaderno cuadriculado grande",
            "Cuaderno rayado grande",
            "Cúter",
            "Etiqueta sin cambio ni devolución",
            "Etiqueta Zebra 250x800",
            "Etiqueta Zebra 50x25 térmica eco x250u",
            "Etiquetadora precio",
            "Fibrón punta cuadrada negro",
            "Fibrón punta cuadrada rojo",
            "Folio oficio",
            "Guías internas",
            "Goma",
            "Lapicera azul",
            "Lapicera negra",
            "Lápiz negro",
            "Moño mágico op. x100u N°25 plata",
            "Moño mágico op. x100u N°25 rojo",
            "Moño mágico op. x50u N°50 plata",
            "Moño mágico op. x50u N°50 rojo",
            "Precio autoadhesivo efectivo/tarjeta",
            "Precio oportunidad calzado",
            "Precio oportunidad indumentaria",
            "Regla 30 cm",
            "Resaltador amarillo",
            "Resma A4 Nat",
            "Rollo de film negro",
            "Rollo de film transparente",
            "Rollo fiscal térmico Dexter",
            "Rollo fiscal térmico Moov",
            "Rollo fiscal térmico Stock Center",
            "Rollo para etiquetadora amarillo",
            "Rollo para etiquetadora blanco",
            "Rollo para etiquetadora verde",
            "Rollo termocontraíble",
            "Sacapuntas",
            "Sobre papel madera 19x24",
            "Sobre papel madera 30x40",
            "Tacos",
            "Talonario comprobantes de gastos",
            "Talonario de memorándum",
            "Talonario vale a descontar",
            "Tijera",
            "Tinta para sello negra",
            "Voligoma",
        ],
    },
    {
        "nombre": "Insumos Limpieza",
        "items": [
            "Algodón",
            "Armazón mopa 1m",
            "Armazón mopa 60cm",
            "Balde",
            "Bolsa de residuo 45x60",
            "Bolsa de residuo 80x110",
            "Cif crema",
            "Desodorante de ambiente",
            "Detergente 750cc",
            "Escobilla baño",
            "Escobillones chicos",
            "Esponja acero",
            "Esponja amarilla",
            "Franela",
            "Guantes de cocina",
            "Insecticida mata cucarachas/arañas",
            "Insecticida mata mosquitos",
            "Jabón de tocador",
            "Jabón líquido x5 lts",
            "Limpia vidrios Cif",
            "Lustramueble",
            "Pala chica",
            "Palo escoba",
            "Papel higiénico x300m",
            "Papel higiénico x80m",
            "Plumero N°2",
            "Rejilla",
            "Repuesto barredor 1m (mopa)",
            "Repuesto barredor 60cm (mopa)",
            "Secador",
            "Secador de vidrio",
            "Sopapa",
            "Sutter spolvero",
            "Toallas de papel",
            "Trapo de piso",
        ],
    },
]

# Prefijos usados por el portal de Compras (Laura) para filtrar su stock.
INSUMOS_COMPRAS_PREFIX = "Insumos"
INSUMOS_COMPRAS_CATEGORIAS = ["Insumos Librería", "Insumos Limpieza"]
