from pathlib import Path
import re

source = Path('tecman/sucursales_data.py')
text = source.read_text()

updates = {
    '011': ('MV','Moov Moron'),
    '023': ('DX','Dexter Moreno'),
    '028': ('DX','Dexter San Martin Peatonal'),
    '035': ('MV','Moov Merlo'),
    '036': ('DX','Dexter Flores'),
    '043': ('MV','Moov Terrazas de Mayo'),
    '049': ('MV','Moov Alto Avellaneda'),
    '051': ('DX','Dexter San Miguel'),
    '052': ('MV','Moov Lomas'),
    '053': ('DX','Dexter Unicenter'),
    '054': ('DX','Dexter Berazategui'),
    '065': ('DX','Dexter Quilmes Factory'),
    '076': ('MV','Moov Corner Cordoba'),
    '077': ('MV','Moov Lanus'),
    '082': ('DX','Dexter Zarate'),
    '083': ('DX','Dexter Solano'),
    '091': ('DX','Dexter Junin'),
    '092': ('DX','Dexter Tandil'),
    '111': ('DX','Dexter San Fernando'),
    '114': ('DX','Dexter Santa Fe'),
    '116': ('DX','Dexter SG San Nicolas'),
    '126': ('MV','Moov Salta'),
    '127': ('MV','Moov Alto Rosario'),
    '132': ('DX','Dexter Plaza Shopping'),
    '133': ('DX','Dexter Neuquen'),
    '134': ('SC','Stock Center Neuquen'),
    '139': ('DX','Dexter Salta'),
    '141': ('DX','Dexter Escobar'),
    '147': ('DX','Dexter Palmas del Pilar'),
    '148': ('MV','Moov San Martin'),
    '156': ('DX','Dexter SG Abasto'),
    '157': ('SC','Stock Center Portal San Martin'),
    '158': ('DX','Dexter La Rioja Centro'),
    '159': ('MV','Moov San Juan'),
    '160': ('DX','Dexter Trelew'),
    '165': ('MV','Moov Cabildo'),
    '166': ('MV','Moov Rosario Peatonal'),
    '167': ('DX','Dexter Lomas'),
    '170': ('DX','Dexter Caballito'),
    '171': ('SC','Stock Center San Miguel'),
    '172': ('DX','Dexter San Juan'),
    '173': ('SC','Stock Center Tucuman'),
    '176': ('SC','Stock Center Gral Paz'),
    '177': ('SC','Stock Center San Justo'),
    '178': ('DX','Dexter Shopping La Paz'),
    '183': ('DX','Dexter SG Floyco'),
    '184': ('DX','Dexter Cabildo y Juramento'),
    '185': ('SC','Stock Center Parque Brown'),
    '186': ('DX','Dexter Panamericana'),
    '187': ('SC','Stock Center Lomas Center'),
    '188': ('MV','Moov Quilmes'),
    '190': ('SC','Stock Center Soleil'),
    '195': ('SC','Stock Center Gaona'),
    '196': ('DX','Dexter Pacheco'),
    '213': ('DX','Dexter Congreso'),
    '215': ('MV','Moov Cordoba II'),
    '216': ('DX','Dexter Quilmes'),
    '219': ('MV','Moov Unicenter'),
    '220': ('DX','Dexter Corrientes'),
    '221': ('MV','Moov Flores'),
    '222': ('DX','Dexter Moron'),
    '228': ('MV','Moov Varela'),
    '229': ('DX','Dexter Santiago del Estero'),
    '230': ('MV','Moov Tucuman'),
    '231': ('MV','Moov Portal Neuquen'),
    '233': ('DX','Dexter Cordoba 9 de Julio'),
    '234': ('MV','Moov Parque Brown'),
    '235': ('DX','Dexter Jujuy'),
}

for code, (marca, tienda) in updates.items():
    text = re.sub(
        rf'("{code}": \{{"marca": ")[^"]+(", "tienda": ")[^"]+(")',
        rf'\1{marca}\2{tienda}\3',
        text,
        count=1,
    )

source.write_text(text)
print('ok')
